/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ReadAndLearn.Login;

import Database.Users;
import Database.*;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;


public class CreateAccount extends javax.swing.JFrame {
    
     //---------------------
    Users user;
    
    //----------------------
    int userType = 1;

    public CreateAccount() {
        initComponents();
        makeErrorStarsInvisible();
          user = new Users();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        jPanel4 = new javax.swing.JPanel();
        PanelMiddle = new javax.swing.JPanel();
        PanelFieldEnclosure = new javax.swing.JPanel();
        lblStarEmail = new javax.swing.JLabel();
        lblFirstName = new javax.swing.JLabel();
        lblStarPassword = new javax.swing.JLabel();
        txtConfirmPasword = new javax.swing.JPasswordField();
        lblStarLastName = new javax.swing.JLabel();
        lblStarConfirmPassword = new javax.swing.JLabel();
        txtFirstName = new javax.swing.JTextField();
        lblConfirmPassword = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        txtEmail = new javax.swing.JTextField();
        txtLastName = new javax.swing.JTextField();
        lblLastName = new javax.swing.JLabel();
        txtPassword = new javax.swing.JPasswordField();
        lblPassword = new javax.swing.JLabel();
        lblStarFirstName = new javax.swing.JLabel();
        btnNext = new javax.swing.JButton();
        checkBoxSignupAsProfessor = new javax.swing.JCheckBox();
        PanelPasswordInstructions = new javax.swing.JPanel();
        lblInstructionheading = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        PanelBottom = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        PanelTop = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(900, 700));
        setResizable(false);

        PanelMiddle.setBackground(new java.awt.Color(102, 102, 102));

        PanelFieldEnclosure.setBackground(new java.awt.Color(102, 102, 102));

        lblStarEmail.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStarEmail.setForeground(new java.awt.Color(255, 0, 0));
        lblStarEmail.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStarEmail.setText("*");

        lblFirstName.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblFirstName.setForeground(new java.awt.Color(255, 255, 255));
        lblFirstName.setText("First Name");

        lblStarPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStarPassword.setForeground(new java.awt.Color(255, 0, 0));
        lblStarPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStarPassword.setText("*");

        lblStarLastName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStarLastName.setForeground(new java.awt.Color(255, 0, 0));
        lblStarLastName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStarLastName.setText("*");

        lblStarConfirmPassword.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStarConfirmPassword.setForeground(new java.awt.Color(255, 0, 0));
        lblStarConfirmPassword.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStarConfirmPassword.setText("*");

        lblConfirmPassword.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblConfirmPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblConfirmPassword.setText("Confirm Password");

        lblEmail.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblEmail.setForeground(new java.awt.Color(255, 255, 255));
        lblEmail.setText("Email");

        lblLastName.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblLastName.setForeground(new java.awt.Color(255, 255, 255));
        lblLastName.setText("Last Name");

        lblPassword.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        lblPassword.setForeground(new java.awt.Color(255, 255, 255));
        lblPassword.setText("Password");

        lblStarFirstName.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblStarFirstName.setForeground(new java.awt.Color(255, 0, 0));
        lblStarFirstName.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStarFirstName.setText("*");

        btnNext.setFont(new java.awt.Font("Segoe UI", 1, 11)); // NOI18N
        btnNext.setText("Create Account");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        checkBoxSignupAsProfessor.setBackground(new java.awt.Color(102, 102, 102));
        checkBoxSignupAsProfessor.setFont(new java.awt.Font("Segoe UI", 2, 14)); // NOI18N
        checkBoxSignupAsProfessor.setForeground(new java.awt.Color(255, 255, 255));
        checkBoxSignupAsProfessor.setText("I am a Professor? (Requires further verification from the Administrator)");
        checkBoxSignupAsProfessor.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                checkBoxSignupAsProfessorItemStateChanged(evt);
            }
        });

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, PanelMiddle, org.jdesktop.beansbinding.ELProperty.create("${background}"), PanelPasswordInstructions, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        lblInstructionheading.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblInstructionheading.setForeground(new java.awt.Color(255, 255, 255));
        lblInstructionheading.setText("PASSWORD INSTRUCTIONS");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setText("Password must me atleast 8 characters long");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lblInstructionheading, org.jdesktop.beansbinding.ELProperty.create("${foreground}"), jLabel4, org.jdesktop.beansbinding.BeanProperty.create("foreground"));
        bindingGroup.addBinding(binding);

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setText("Password must have an uppercase leter and a lowecase letter ");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lblInstructionheading, org.jdesktop.beansbinding.ELProperty.create("${foreground}"), jLabel5, org.jdesktop.beansbinding.BeanProperty.create("foreground"));
        bindingGroup.addBinding(binding);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setText("Password must have a special character and a number");

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, lblInstructionheading, org.jdesktop.beansbinding.ELProperty.create("${foreground}"), jLabel6, org.jdesktop.beansbinding.BeanProperty.create("foreground"));
        bindingGroup.addBinding(binding);

        javax.swing.GroupLayout PanelPasswordInstructionsLayout = new javax.swing.GroupLayout(PanelPasswordInstructions);
        PanelPasswordInstructions.setLayout(PanelPasswordInstructionsLayout);
        PanelPasswordInstructionsLayout.setHorizontalGroup(
            PanelPasswordInstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPasswordInstructionsLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelPasswordInstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblInstructionheading, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        PanelPasswordInstructionsLayout.setVerticalGroup(
            PanelPasswordInstructionsLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelPasswordInstructionsLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(lblInstructionheading, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addGap(18, 18, 18)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelFieldEnclosureLayout = new javax.swing.GroupLayout(PanelFieldEnclosure);
        PanelFieldEnclosure.setLayout(PanelFieldEnclosureLayout);
        PanelFieldEnclosureLayout.setHorizontalGroup(
            PanelFieldEnclosureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFieldEnclosureLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(PanelFieldEnclosureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFieldEnclosureLayout.createSequentialGroup()
                        .addGroup(PanelFieldEnclosureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxSignupAsProfessor)
                            .addComponent(lblConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelFieldEnclosureLayout.createSequentialGroup()
                                .addGap(2, 2, 2)
                                .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStarEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelFieldEnclosureLayout.createSequentialGroup()
                                .addGroup(PanelFieldEnclosureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(btnNext, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 335, Short.MAX_VALUE)
                                    .addComponent(txtConfirmPasword)
                                    .addComponent(txtPassword))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(PanelFieldEnclosureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblStarConfirmPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblStarPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 394, Short.MAX_VALUE))
                    .addGroup(PanelFieldEnclosureLayout.createSequentialGroup()
                        .addGroup(PanelFieldEnclosureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(PanelFieldEnclosureLayout.createSequentialGroup()
                                .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStarFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(PanelFieldEnclosureLayout.createSequentialGroup()
                                .addGroup(PanelFieldEnclosureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 335, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lblStarLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(PanelPasswordInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        PanelFieldEnclosureLayout.setVerticalGroup(
            PanelFieldEnclosureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelFieldEnclosureLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PanelFieldEnclosureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(PanelFieldEnclosureLayout.createSequentialGroup()
                        .addComponent(lblFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(2, 2, 2)
                        .addGroup(PanelFieldEnclosureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStarFirstName))
                        .addGap(7, 7, 7)
                        .addComponent(lblLastName)
                        .addGap(2, 2, 2)
                        .addGroup(PanelFieldEnclosureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblStarLastName))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblEmail))
                    .addComponent(PanelPasswordInstructions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFieldEnclosureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtEmail, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStarEmail))
                .addGap(18, 18, 18)
                .addComponent(lblPassword)
                .addGap(1, 1, 1)
                .addGroup(PanelFieldEnclosureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStarPassword))
                .addGap(18, 18, 18)
                .addComponent(lblConfirmPassword)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(PanelFieldEnclosureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtConfirmPasword, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStarConfirmPassword))
                .addGap(18, 18, 18)
                .addComponent(checkBoxSignupAsProfessor)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnNext, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout PanelMiddleLayout = new javax.swing.GroupLayout(PanelMiddle);
        PanelMiddle.setLayout(PanelMiddleLayout);
        PanelMiddleLayout.setHorizontalGroup(
            PanelMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMiddleLayout.createSequentialGroup()
                .addComponent(PanelFieldEnclosure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(52, Short.MAX_VALUE))
        );
        PanelMiddleLayout.setVerticalGroup(
            PanelMiddleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelMiddleLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(PanelFieldEnclosure, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, PanelTop, org.jdesktop.beansbinding.ELProperty.create("${background}"), PanelBottom, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Already have an account? Click Login.");

        jButton1.setText("Login");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogin(evt);
            }
        });

        javax.swing.GroupLayout PanelBottomLayout = new javax.swing.GroupLayout(PanelBottom);
        PanelBottom.setLayout(PanelBottomLayout);
        PanelBottomLayout.setHorizontalGroup(
            PanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBottomLayout.createSequentialGroup()
                .addGap(293, 293, 293)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        PanelBottomLayout.setVerticalGroup(
            PanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelBottomLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(PanelBottomLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap())
        );

        PanelTop.setBackground(new java.awt.Color(102, 0, 0));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Create New Account");

        javax.swing.GroupLayout PanelTopLayout = new javax.swing.GroupLayout(PanelTop);
        PanelTop.setLayout(PanelTopLayout);
        PanelTopLayout.setHorizontalGroup(
            PanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        PanelTopLayout.setVerticalGroup(
            PanelTopLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PanelTopLayout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(PanelMiddle, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(PanelTop, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(PanelTop, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelMiddle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(PanelBottom, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        
        if(checkBlanks())
        {
            JOptionPane.showMessageDialog(null, "ERROR! : Please enter all fields!","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!passwordsMatch())
        {
            JOptionPane.showMessageDialog(null, "ERROR! : Passwords does not match!","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(!isEmailFormatCorrect())
        {
            JOptionPane.showMessageDialog(null, "Please enter correct Email","Error", JOptionPane.ERROR_MESSAGE);
            return;
        }
        
        if(txtFirstName.getText().isEmpty())
        {
            System.out.println("EMPTY NAME");
        }
        if(user.insertUser(txtFirstName.getText(), txtLastName.getText(), txtEmail.getText(), String.valueOf(txtPassword.getPassword()), userType))
         {
             JOptionPane.showMessageDialog(null, "Registration Successful. Click OK to go to Login.","Success", JOptionPane.INFORMATION_MESSAGE);
             login();
             
         }
        else
        {
           JOptionPane.showMessageDialog(null, "ERROR! : Email already in use. Please enter a different email address.","Error", JOptionPane.ERROR_MESSAGE);
            return; 
        }
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnLogin(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogin
        login();
    }//GEN-LAST:event_btnLogin
    
    private void login()
    {
        Login loginForm = new Login();
        loginForm.pack();
        loginForm.setLocationRelativeTo(null);
        loginForm.setVisible(true);
        this.dispose();        
    }
    
    
    private void checkBoxSignupAsProfessorItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_checkBoxSignupAsProfessorItemStateChanged
        if(checkBoxSignupAsProfessor.isSelected())
        {
            userType = 3;            
        }
        else userType = 1;
    }//GEN-LAST:event_checkBoxSignupAsProfessorItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CreateAccount.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CreateAccount().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PanelBottom;
    private javax.swing.JPanel PanelFieldEnclosure;
    private javax.swing.JPanel PanelMiddle;
    private javax.swing.JPanel PanelPasswordInstructions;
    private javax.swing.JPanel PanelTop;
    private javax.swing.JButton btnNext;
    private javax.swing.JCheckBox checkBoxSignupAsProfessor;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel lblConfirmPassword;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblFirstName;
    private javax.swing.JLabel lblInstructionheading;
    private javax.swing.JLabel lblLastName;
    private javax.swing.JLabel lblPassword;
    private javax.swing.JLabel lblStarConfirmPassword;
    private javax.swing.JLabel lblStarEmail;
    private javax.swing.JLabel lblStarFirstName;
    private javax.swing.JLabel lblStarLastName;
    private javax.swing.JLabel lblStarPassword;
    private javax.swing.JPasswordField txtConfirmPasword;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtFirstName;
    private javax.swing.JTextField txtLastName;
    private javax.swing.JPasswordField txtPassword;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    /**
     * Makes all the stars invisible
     */
    private void makeErrorStarsInvisible() {
        lblStarFirstName.setVisible(false);
        lblStarLastName.setVisible(false);
        lblStarEmail.setVisible(false);
        lblStarPassword.setVisible(false);
        lblStarConfirmPassword.setVisible(false);
    }

   private boolean checkBlanks() {
        boolean isEmpty = false;
        
        if(txtFirstName.getText().isEmpty())
        {
            isEmpty = true;
            lblStarFirstName.setVisible(true);
        }
        
        if(txtLastName.getText().isEmpty())
        {
            isEmpty = true;
            lblStarLastName.setVisible(true);
        }
        
        if(txtEmail.getText().isEmpty())
        {
            isEmpty = true;
            lblStarEmail.setVisible(true);
        }
        
        if(String.valueOf(txtPassword.getPassword()).isEmpty())
        {
            isEmpty = true;
            lblStarPassword.setVisible(true);
        }
        
        if(String.valueOf(txtConfirmPasword.getPassword()).isEmpty())
        {
            isEmpty = true;
            lblStarConfirmPassword.setVisible(true);
        }
        return isEmpty;
    }

    private boolean passwordsMatch() {
        return (String.valueOf(txtPassword.getPassword()).equals(String.valueOf(txtConfirmPasword.getPassword())));        
    }

    private boolean isEmailFormatCorrect() {
        String emailRegex = "\\w+([-+.']\\w+)*@\\w+([-.]\\w+)*\\.\\w+([-.]\\w+)*";
        Pattern checkEmailPattern = Pattern.compile(emailRegex);
        Matcher emailMatcher = checkEmailPattern.matcher(txtEmail.getText());
        return (emailMatcher.matches());
    }
}
